name: SAM Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: sam build --use-container
      - name: SAM Deploy
        run: |
          # Run SAM Deploy
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset \
            --parameter-overrides \
              'UserPoolId=${{ secrets.USER_POOL_ID }},UserPoolAWSRegion=${{ secrets.USER_POOL_AWS_REGION }}'

# Workflow baseado nos exemplos fornecidos pela documentação da AWS em 
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/deploying-using-github.html
# https://github.com/aws-samples/aws-sam-github-actions-example/tree/main
