name: SAM Validate and Build
on:
  pull_request:
    branches: [ main ]

jobs:
  sam-validate-build-test:
    runs-on: ubuntu-latest
    outputs:
      env-name: ${{ steps.env-name.outputs.environment }}
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: SAM Validate
        run: |
          sam validate
      - name: SAM Build
        run: |
          # Run SAM Build
            --parameter-overrides \
              'UserPoolId=${{ secrets.USER_POOL_ID }},UserPoolAWSRegion=${{ secrets.USER_POOL_AWS_REGION }}'

# Workflow baseado nos exemplos fornecidos pela documentação da AWS em 
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/deploying-using-github.html
# https://github.com/aws-samples/aws-sam-github-actions-example/tree/main
